#region BSD License
/* FlatFour.Platform - PlatformDefs.cs
 * Copyright (c) 2001-2006 Jason Perkins.
 * All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the BSD-style license that is 
 * included with this library in the file LICENSE.txt.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * files LICENSE.txt for more details. */
#endregion

using System;

namespace FlatFour.Platform
{
	public delegate void InputHandler(InputEventArgs args);
	public delegate void TickHandler();

	public enum Key
	{
		Unknown,
		Escape,
		One,
		Two,
		Three,
		Four,
		Five,
		Six,
		Seven,
		Eight,
		Nine,
		Zero,
		Minus,
		Equals,
		Backspace,
		Tab,
		Q,
		W,
		E,
		R,
		T,
		Y,
		U,
		I,
		O,
		P,
		LeftBracket,
		RightBracket,
		Enter,
		LeftControl,
		A,
		S,
		D,
		F,
		G,
		H,
		J,
		K,
		L,
		Semicolon,
		Apostrophe,
		Grave,
		LeftShift,
		Backslash,
		Z,
		X,
		C,
		V,
		B,
		N,
		M,
		Comma,
		Period,
		Slash,
		RightShift,
		NumPadMultiply,
		LeftAlt,
		Space,
		CapsLock,
		F1,
		F2,
		F3,
		F4,
		F5,
		F6,
		F7,
		F8,
		F9,
		F10,
		NumLock,
		ScrollLock,
		NumPad7,
		NumPad8,
		NumPad9,
		NumPadMinus,
		NumPad4,
		NumPad5,
		NumPad6,
		NumPadPlus,
		NumPad1,
		NumPad2,
		NumPad3,
		NumPad0,
		NumPadDecimal,
		OEM102,
		F11,
		F12,
		F13 = 0x64,
		F14,
		F15,
		Kana = 0x70,
		ABNTC1 = 0x73,
		Convert = 0x79,
		NoConvert = 0x7b,
		Yen = 0x7d,
		ABNTC2,
		NumPadEquals = 0x8d,
		PrevTrack = 0x90,
		At,
		Colon,
		Underline,
		Kanji,
		Stop,
		AX,
		Unlabeled,
		NextTrack = 0x99,
		NumPadEnter= 0x9c,
		RightControl,
		Mute = 0xa0,
		Calculator,
		PlayPause,
		MediaStop = 0xa4,
		VolumeDown = 0xae,
		VolumeUp = 0xb0,
		WebHome = 0xb2,
		NumPadComma,
		NumPadDivide = 0xb5,
		SysRq = 0xb7,
		RightAlt,
		Pause = 0xc5,
		Home = 0xc7,
		Up,
		PageUp,
		Left = 0xcb,
		Right = 0xcd,
		End = 0xcf,
		Down,
		PageDown,
		Insert,
		Delete,
		LeftSystem = 0xdb,
		RightSystem,
		Menu,
		Power,
		Sleep,
		Wake = 0xe3,
		WebSearch = 0xe5,
		WebFavorites,
		WebRefresh,
		WebStop,
		WebForward,
		WebBack,
		MyComputer,
		Mail,
		MediaSelect
	}
}
